### ISSUE TITLE
EC05 failing

### ISSUE THREAD

**Issue by diggit** [KiCad/kicad-library-utils#61]
```
checklib.py  -vvv  --enable-extra library/device.lib

Traceback (most recent call last):
  File "/home/diggit/dev/kicad-library-utils/schlib/checklib.py", line 131, in <module>
    if ec.check():
  File "/home/diggit/dev/kicad-library-utils/schlib/rules/EC05.py", line 53, in check
    for i in range(1, max(pins.keys()) + 1):
ValueError: max() arg is an empty sequence
```

on kicad-library PR 742

Also fails for component with non numerical pin numbers like BGAs.

**Comment by ricardocrudo** [comment]
Fixed at f68599e. Thanks Patrik.
